const DEPTH_PERCEPTION = 1;

export const PARAMS = {
	DIMENSION: '2D',
	NB_FISH: 200 / DEPTH_PERCEPTION,
	MAX_ROTATION: 2 * Math.PI / 200,
	SPEED_LOSS: .05 * DEPTH_PERCEPTION,
	ACCELERATION: .1 * DEPTH_PERCEPTION,
	MIN_SPEED: .5 * DEPTH_PERCEPTION,
	MAX_SPEED: 2 * DEPTH_PERCEPTION,
	MAX_VISION_DISTANCE: 50 * DEPTH_PERCEPTION,
};